import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";

import Special_menu from "./Special_menu";
import Form from "./Form";

export default function Home() {
  const [lang, setLang] = useState("ru");

  const langs = {
    ["ru"]: {
      h1: "Авторизация",
      li: [
        { label: "Русский", key: "ru" },
        { label: "Английский", key: "en" },
        { label: "Корейский", key: "kor" },
        { label: "asdfa", key: "jap" },
        { label: "asdafwefa", key: "bla" },
      ],
      email: "Ваш e-mail",
      password: "Пароль",
      button: "Отправить",
    },
    ["en"]: {
      h1: "Avtorisation",
      li: [
        { label: "Russian", key: "ru" },
        { label: "English", key: "en" },
        { label: "Korean", key: "kor" },
        { label: "asdfa", key: "jap" },
        { label: "asdafwefa", key: "bla" },
      ],
      email: "E-mail",
      password: "Password",
      button: "Submit",
    },
    ["kor"]: {
      h1: "Bla",
      li: [
        { label: "blasРусский", key: "ru" },
        { label: "LagАнглийский", key: "en" },
        { label: "fsdКорейский", key: "kor" },
        { label: "asdfa", key: "jap" },
        { label: "asdafwefa", key: "bla" },
      ],
      email: "Bla e-mail",
      password: " blaПароль",
      button: "BlaОтправить",
    },
    ["jap"]: {
      h1: "Авторизация",
      li: [
        { label: "Русdsfaский", key: "ru" },
        { label: "Английfdasский", key: "en" },
        { label: "Кореdsafйский", key: "kor" },
        { label: "asdfa", key: "jap" },
        { label: "asdafwefa", key: "bla" },
      ],
      email: "Ваш e-mail",
      password: "Пароль",
      button: "Отправить",
    },
    ["bla"]: {
      h1: "Авторизация",
      li: [
        { label: "Русfasский", key: "ru" },
        { label: "Англиfawйский", key: "en" },
        { label: "Кореafeйский", key: "kor" },
        { label: "asdafwefa", key: "jap" },
        { label: "asdafwefa", key: "bla" },
      ],
      email: "Ваш e-mail",
      password: "Пароль",
      button: "Отправить",
    },
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Special_menu langs={langs} lang={lang} setLang={setLang} />
      <Form
        email={langs[lang].email}
        password={langs[lang].password}
        button={langs[lang].button}
      />
    </div>
  );
}
